#ifndef BBCODETAGINVALIDNESS_H_
#define BBCODETAGINVALIDNESS_H_

enum BBCodeTagInvalidness {
    BBCODE_VALID,
    BBCODE_NO_CLOSING_TAG,
    BBCODE_OUT_OF_PLACE_CLOSING_TAG
};

#endif // BBCODETAGINVALIDNESS_H_
